Controllers/AccountingController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using samadApp.Models.DataTransportObject;
using samadApp.Models;
namespace samadApp.Controllers
{
    // [Route("[controller]")]
    public class AccountingController : Controller
    {
        private readonly UserManager<Users> _userManager;
        private readonly SignInManager<Users> _signInManager;
        private readonly ILogger<AccountingController> _logger;

        public AccountingController(ILogger<AccountingController> logger,SignInManager<Users> signInManager,UserManager<Users> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult RegisterAction(){
            return View("Register");
        }
        [HttpPost]
        public IActionResult RegisterAction(Register register){
           
            if(ModelState.IsValid == false){
                return View("Register");
            }
            Users newUser= new Users(){
                Fname= register.Fname,
                Lname= register.Lname,
                Email = register.Email,
                UserName = register.Email,
                College = register.College
            };
           
            var result = _userManager.CreateAsync(newUser,register.Password).Result;
            if (result.Succeeded){
                return RedirectToAction("Index","Home");
            }
            string messageRegister = "";
            foreach (var item in result.Errors.ToList())
            {
                messageRegister += item.Description + Environment.NewLine;
            }
            TempData["MessageRegister"] = messageRegister;
            return View("Register");
        }


        [HttpGet]
        public IActionResult Login(){
            return View();
        } 

        [HttpPost]
        public async Task<IActionResult> Login(LoginDto loginDto){
            if(!ModelState.IsValid){
                return View(loginDto);
            }
            var user = _userManager.FindByNameAsync(loginDto.UserName).Result;
            if(user == null){
                TempData["MessageLogin"] = "نام کاربری یا کلمه عبور اشتباه است";
            }
            _signInManager.SignOutAsync();
            
            //login proccess 
            var result = _signInManager.PasswordSignInAsync(loginDto.UserName,loginDto.Password,loginDto.RememmberMe,true).Result;
        
             
            if(result.Succeeded){
                ViewBag.LogedinUserName = user.Fname +" "+user.Lname;
                return RedirectToAction("Index","Home");
            }else{
                TempData["MessageLogin"] = "نام کاربری یا کلمه عبور اشتباه است";
                if(result.IsLockedOut){
                    ModelState.AddModelError(string.Empty," اکانت شما قفل شده است ");
                    TempData["MessageLogin"] = " اکانت شما قفل شده است ";
                } 
                ModelState.AddModelError(string.Empty,"مشکل در ورود");
                return View(loginDto);
               
            }

            
           

           

            //return View(loginDto);
            
        } 

        public IActionResult Logout(){
            _signInManager.SignOutAsync();
            //RedirectToAction("Login","Accounting");
            return View("Login");
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - samadApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.rtl.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/samadApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav style="direction: rtl; text-align:right"class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-success border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SAMAD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"> @ViewBag.LogedinUserName </span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">خانه</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Accounting" asp-action="Logout">خروج</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Buy">خرید</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Sell">فروش</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
   

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 1402 - Samad Trade 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_LayoutAccount.cshtml
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   
    <link rel="stylesheet" href="~/css/login.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <!-- CSS only -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.2/css/bootstrap.css"
    />
    <link
      rel="stylesheet"
      href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap4.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <title>@ViewData["Title"] - SAMAD</title>
  </head>
  <body>
    <div class="container">
        @RenderBody()
    </div>

  </body>
</html>

   
   